#!/usr/bin/python

import os, sys
import time
import subprocess
import random

nxDirectory = os.getcwd()
path = os.path.dirname(sys.argv[0])
pathname = os.path.abspath(path)

print nxDirectory
print pathname

subprocess.Popen("jackd -dalsa -dhw:0 -r44100 -p1024 -n2", shell=True)

time.sleep(10)

subprocess.Popen("pd-extended", shell=True)
